name: Update README stats
on:
  schedule:
    - cron: '0 * * * *' # chaque heure
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate stats
        uses: brencarter/github-readme-stats-action@v1
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          username: cedric-navet
          count_private: true
          include_all_commits: true
      - name: Commit and push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "actions@github.com"
          git add README.md
          git commit -m "♻️ Update stats" || echo "Nothing to commit"
          git push
